# Generated by Django 4.2.6 on 2023-10-29 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_rol_options_alter_user_rol_alter_rol_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rol',
            table=None,
        ),
    ]
